/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddToCartInput {
  'dob' : string,
  'sampleSelected' : string,
  'name' : string,
  'description' : string,
  'deliveryTime' : string,
  'email' : string,
  'gender' : Gender,
  'brandName' : string,
  'phone' : string,
  'price' : string,
  'product' : string,
}
export interface BasicProfile { 'fullName' : string, 'email' : string }
export interface ConfirmationEmailRequest {
  'confirmationMessageTemplate' : string,
  'orderId' : bigint,
  'timestamp' : Time,
  'customerEmail' : string,
}
export interface ExpandedOrder {
  'id' : bigint,
  'dob' : string,
  'paymentStatus' : PaymentStatus,
  'sampleSelected' : string,
  'orderStatus' : OrderStatus,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'deliveryTime' : string,
  'email' : string,
  'gender' : Gender,
  'timestamp' : Time,
  'brandName' : string,
  'phone' : string,
  'price' : string,
  'product' : string,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface NotificationRequest {
  'sample' : string,
  'name' : string,
  'description' : string,
  'email' : string,
  'timestamp' : Time,
  'brandName' : string,
  'phone' : string,
  'product' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'paidSubmitted' : null } |
  { 'confirmed' : null } |
  { 'failed' : null };
export interface ProductBannerSample {
  'file' : ExternalBlob,
  'description' : string,
}
export interface ProductBannerSampleUpdate {
  'sample' : [] | [ProductBannerSample],
  'position' : bigint,
}
export interface ProductBanners {
  'sample1' : [] | [ProductBannerSample],
  'sample2' : [] | [ProductBannerSample],
  'sample3' : [] | [ProductBannerSample],
  'sample4' : [] | [ProductBannerSample],
}
export interface Sample {
  'description' : string,
  'sampleName' : string,
  'concentration' : string,
  'price' : string,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'deliveryTime' : string,
  'priceUSD' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportRequest {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'dob' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isVerified' : boolean,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSample' : ActorMethod<[string, string, string, string], undefined>,
  'addService' : ActorMethod<[string, bigint, string], bigint>,
  'addToCart' : ActorMethod<[AddToCartInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteNotificationRequest' : ActorMethod<[bigint], undefined>,
  'getAllConfirmationEmailRequests' : ActorMethod<
    [],
    Array<ConfirmationEmailRequest>
  >,
  'getAllNotificationRequests' : ActorMethod<[], Array<NotificationRequest>>,
  'getCallerOrders' : ActorMethod<[], Array<ExpandedOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmationMessageTemplate' : ActorMethod<[], string>,
  'getCustomerOrders' : ActorMethod<[string], Array<ExpandedOrder>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<ExpandedOrder>>,
  'getProductBannerSamples' : ActorMethod<[], ProductBanners>,
  'getSamples' : ActorMethod<[], Array<Sample>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportRequests' : ActorMethod<[], Array<SupportRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveBasicProfile' : ActorMethod<[BasicProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitConfirmationEmailRequest' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'submitSupportRequest' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderPaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProductBannerSamples' : ActorMethod<
    [Array<ProductBannerSampleUpdate>],
    undefined
  >,
  'verifyPaymentAndConfirmOrder' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];