/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const AddToCartInput = IDL.Record({
  'dob' : IDL.Text,
  'sampleSelected' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'price' : IDL.Text,
  'product' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const ConfirmationEmailRequest = IDL.Record({
  'confirmationMessageTemplate' : IDL.Text,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'customerEmail' : IDL.Text,
});
export const NotificationRequest = IDL.Record({
  'sample' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'product' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'paidSubmitted' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ExpandedOrder = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'sampleSelected' : IDL.Text,
  'orderStatus' : OrderStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'timestamp' : Time,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'price' : IDL.Text,
  'product' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dob' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'gender' : Gender,
});
export const Sample = IDL.Record({
  'description' : IDL.Text,
  'sampleName' : IDL.Text,
  'concentration' : IDL.Text,
  'price' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'priceUSD' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SupportRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const BasicProfile = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSample' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addToCart' : IDL.Func([AddToCartInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteNotificationRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllConfirmationEmailRequests' : IDL.Func(
      [],
      [IDL.Vec(ConfirmationEmailRequest)],
      ['query'],
    ),
  'getAllNotificationRequests' : IDL.Func(
      [],
      [IDL.Vec(NotificationRequest)],
      ['query'],
    ),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(ExpandedOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfirmationMessageTemplate' : IDL.Func([], [IDL.Text], ['query']),
  'getCustomerOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExpandedOrder)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(ExpandedOrder)],
      ['query'],
    ),
  'getSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBasicProfile' : IDL.Func([BasicProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitConfirmationEmailRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitSupportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderPaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'verifyPaymentAndConfirmOrder' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const AddToCartInput = IDL.Record({
    'dob' : IDL.Text,
    'sampleSelected' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'price' : IDL.Text,
    'product' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const ConfirmationEmailRequest = IDL.Record({
    'confirmationMessageTemplate' : IDL.Text,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'customerEmail' : IDL.Text,
  });
  const NotificationRequest = IDL.Record({
    'sample' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'product' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'paidSubmitted' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ExpandedOrder = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'sampleSelected' : IDL.Text,
    'orderStatus' : OrderStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'timestamp' : Time,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'price' : IDL.Text,
    'product' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dob' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'gender' : Gender,
  });
  const Sample = IDL.Record({
    'description' : IDL.Text,
    'sampleName' : IDL.Text,
    'concentration' : IDL.Text,
    'price' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'priceUSD' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SupportRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const BasicProfile = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSample' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addToCart' : IDL.Func([AddToCartInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteNotificationRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllConfirmationEmailRequests' : IDL.Func(
        [],
        [IDL.Vec(ConfirmationEmailRequest)],
        ['query'],
      ),
    'getAllNotificationRequests' : IDL.Func(
        [],
        [IDL.Vec(NotificationRequest)],
        ['query'],
      ),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(ExpandedOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfirmationMessageTemplate' : IDL.Func([], [IDL.Text], ['query']),
    'getCustomerOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExpandedOrder)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(ExpandedOrder)],
        ['query'],
      ),
    'getSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBasicProfile' : IDL.Func([BasicProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitConfirmationEmailRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitSupportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderPaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'verifyPaymentAndConfirmOrder' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };