/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const AddToCartInput = IDL.Record({
  'dob' : IDL.Text,
  'sampleSelected' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'price' : IDL.Text,
  'product' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const NotificationRequest = IDL.Record({
  'sample' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'product' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ExpandedOrder = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'sampleSelected' : IDL.Text,
  'orderStatus' : OrderStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'timestamp' : Time,
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'price' : IDL.Text,
  'product' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dob' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'gender' : Gender,
});
export const Sample = IDL.Record({
  'description' : IDL.Text,
  'sampleName' : IDL.Text,
  'concentration' : IDL.Text,
  'price' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'priceRange' : IDL.Text,
});
export const SupportRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSample' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addToCart' : IDL.Func([AddToCartInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNotificationRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllNotificationRequests' : IDL.Func(
      [],
      [IDL.Vec(NotificationRequest)],
      ['query'],
    ),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(ExpandedOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExpandedOrder)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(ExpandedOrder)],
      ['query'],
    ),
  'getSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitSupportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrderPaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const AddToCartInput = IDL.Record({
    'dob' : IDL.Text,
    'sampleSelected' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'price' : IDL.Text,
    'product' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const NotificationRequest = IDL.Record({
    'sample' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'product' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ExpandedOrder = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'sampleSelected' : IDL.Text,
    'orderStatus' : OrderStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'timestamp' : Time,
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'price' : IDL.Text,
    'product' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dob' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'gender' : Gender,
  });
  const Sample = IDL.Record({
    'description' : IDL.Text,
    'sampleName' : IDL.Text,
    'concentration' : IDL.Text,
    'price' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'priceRange' : IDL.Text,
  });
  const SupportRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSample' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addToCart' : IDL.Func([AddToCartInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNotificationRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllNotificationRequests' : IDL.Func(
        [],
        [IDL.Vec(NotificationRequest)],
        ['query'],
      ),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(ExpandedOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExpandedOrder)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(ExpandedOrder)],
        ['query'],
      ),
    'getSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitSupportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateOrderPaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };