/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddToCartInput {
  'dob' : string,
  'sampleSelected' : string,
  'name' : string,
  'description' : string,
  'deliveryTime' : string,
  'email' : string,
  'gender' : Gender,
  'brandName' : string,
  'phone' : string,
  'price' : string,
  'product' : string,
}
export interface ExpandedOrder {
  'id' : bigint,
  'dob' : string,
  'paymentStatus' : string,
  'sampleSelected' : string,
  'orderStatus' : OrderStatus,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'deliveryTime' : string,
  'email' : string,
  'gender' : Gender,
  'timestamp' : Time,
  'brandName' : string,
  'phone' : string,
  'price' : string,
  'product' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface NotificationRequest {
  'sample' : string,
  'name' : string,
  'description' : string,
  'email' : string,
  'timestamp' : Time,
  'brandName' : string,
  'phone' : string,
  'product' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Sample {
  'description' : string,
  'sampleName' : string,
  'concentration' : string,
  'price' : string,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'deliveryTime' : string,
  'priceRange' : string,
}
export interface SupportRequest {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'dob' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isVerified' : boolean,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSample' : ActorMethod<[string, string, string, string], undefined>,
  'addService' : ActorMethod<[string, string, string], bigint>,
  'addToCart' : ActorMethod<[AddToCartInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNotificationRequest' : ActorMethod<[bigint], undefined>,
  'getAllNotificationRequests' : ActorMethod<[], Array<NotificationRequest>>,
  'getCallerOrders' : ActorMethod<[], Array<ExpandedOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[string], Array<ExpandedOrder>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<ExpandedOrder>>,
  'getSamples' : ActorMethod<[], Array<Sample>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSupportRequests' : ActorMethod<[], Array<SupportRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitSupportRequest' : ActorMethod<[string, string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];